name: GitHub Actions to Dockerhub
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: build and tag image
        run: docker build Dockerfile . --tag yohannespetrick/test-action-cc:v1
      - name: push to dockerhub
        run: docker login -u ${{secret.DOCKERHUB_USERNAME}} -p ${{secret.DOCKERHUB_SECRET}} && docker push yohannespetrick/test-action-cc:v1